"""Fetch physical-qubit layout and calibration timestamp for every IBM job the manuscripts cite.

Answers the reviewer request in the PCAE revision (hardware pilot section): which physical
qubits each job ran on, and which calibration was current when it ran. Neither was saved at
submission time, so this reads them back from the service.

    python IBM_Cloud/fetch_job_layouts.py            # jobs the manuscripts cite
    python IBM_Cloud/fetch_job_layouts.py --ledger   # 2026-09 provenance re-campaign jobs

The manuscripts' own job IDs belong to an account that no longer exists (item F2), so they
come back as ``RuntimeJobNotFound``; the report records that. ``--ledger`` instead reads the
IBM jobs of ``outputs/provenance_campaign/ledger.json`` -- the same circuits re-run on the
live account. Those are NEW runs, not the paper's; do not report them as the paper's layouts.

Read-only: retrieves jobs, never submits. The job list comes from
``verify_hardware_jobs.expected_jobs`` so it matches what the manuscripts rely on. IonQ jobs
are skipped (not retrievable through the IBM service).

Physical qubits are read from the submitted ISA circuits (``job.inputs()``): after
transpilation each circuit acts on physical qubit indices, so the qubits touched by
``measure`` instructions are the physical qubits read out. The calibration timestamp is
``backend.properties(datetime=<job start>).last_update_date``.

Writes ``IBM_Cloud/outputs/job_layouts{,_ledger}.{json,md}``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from verify_hardware_jobs import REPO_ROOT, expected_jobs  # noqa: E402

OUT_DIR = REPO_ROOT / "IBM_Cloud" / "outputs"


def measured_qubits(circuit) -> tuple[int, ...]:
    """Physical qubits read out by ``measure`` instructions, in classical-bit order."""
    pairs = []
    for inst in circuit.data:
        if inst.operation.name == "measure":
            q = circuit.find_bit(inst.qubits[0]).index
            c = circuit.find_bit(inst.clbits[0]).index
            pairs.append((c, q))
    return tuple(q for _, q in sorted(pairs))


def pub_circuit(pub):
    if hasattr(pub, "circuit"):
        return pub.circuit
    return pub[0] if isinstance(pub, (tuple, list)) else pub


def fetch(service, record: dict) -> dict:
    job = service.job(record["job_id"])
    out = {**record, "backend_reported": job.backend().name, "status": str(job.status())}
    out["created"] = str(job.creation_date)

    try:
        stamps = job.metrics().get("timestamps", {})
    except Exception as exc:  # noqa: BLE001
        stamps, out["metrics_error"] = {}, repr(exc)
    out["running"] = stamps.get("running")
    out["finished"] = stamps.get("finished")

    try:
        inputs = job.inputs() if callable(job.inputs) else job.inputs
        pubs = inputs.get("pubs", [])
        layouts = [measured_qubits(pub_circuit(p)) for p in pubs]
        distinct = sorted(set(layouts))
        out["n_circuits"] = len(layouts)
        out["layouts"] = [list(l) for l in distinct]
        out["layout_counts"] = [layouts.count(l) for l in distinct]
        out["physical_qubits"] = sorted({q for l in distinct for q in l})
    except Exception as exc:  # noqa: BLE001
        out["layout_error"] = repr(exc)

    try:
        from datetime import datetime, timezone

        when = out["running"] or out["created"]
        when_dt = datetime.fromisoformat(str(when).replace("Z", "+00:00"))
        props = job.backend().properties(datetime=when_dt)
        out["calibration"] = (
            props.last_update_date.astimezone(timezone.utc).isoformat() if props else None
        )
        if props and out.get("physical_qubits"):
            out["readout_error"] = {
                q: round(props.readout_error(q), 4) for q in out["physical_qubits"]
            }
    except Exception as exc:  # noqa: BLE001
        out["calibration_error"] = repr(exc)
    return out


def ledger_jobs() -> list[dict]:
    """IBM jobs of the 2026-09 provenance re-campaign ledger."""
    ledger = json.loads((OUT_DIR / "provenance_campaign" / "ledger.json").read_text())
    jobs = []
    for r in ledger["jobs"]:
        if str(r.get("backend", "")).startswith("ibm_") and r.get("job_id"):
            jobs.append({
                "job_id": r["job_id"],
                "campaign": r.get("stage"),
                "backend": r.get("backend"),
                "shots": r.get("shots"),
                "image": r.get("label"),
            })
    return jobs


def to_markdown(rows: list[dict], title: str, note: str) -> str:
    lines = [
        f"# {title}",
        "",
        note,
        "",
        "Generated by `IBM_Cloud/fetch_job_layouts.py` (read-only fetch from the IBM service).",
        "Physical qubits are the measured qubits of the submitted ISA circuits, in classical-bit",
        "order (c0..c5). Calibration = `backend.properties(datetime=job start).last_update_date`.",
        "Times are UTC.",
        "",
        "| Campaign | Image | Job ID | Backend | Shots | Circuits | Physical qubits used | Distinct layouts | Job ran (UTC) | Calibration (UTC) |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        used = ", ".join(map(str, r["physical_qubits"])) if r.get("physical_qubits") else "n/a"
        lines.append(
            f"| {r.get('campaign')} | {r.get('image') or '—'} | `{r['job_id']}` | "
            f"{r.get('backend_reported') or r.get('backend')} | {r.get('shots')} | "
            f"{r.get('n_circuits', '—')} | {used} | {len(r.get('layouts', [])) or '—'} | "
            f"{r.get('running') or r.get('created') or 'n/a'} | {r.get('calibration') or 'n/a'} |"
        )
    lines += [
        "",
        "The transpiler (optimisation level 1) chose the layout per circuit, so one job spans",
        "several 6-qubit layouts drawn from the qubits listed. Per-circuit layouts",
        "(classical-bit order c0..c5) and counts are in the matching `.json`.",
    ]
    def is_err(k: str) -> bool:
        return k.endswith("_error") and k != "readout_error"

    errs = [r for r in rows if any(is_err(k) for k in r)]
    if errs:
        lines += ["", "## Fetch errors", ""]
        for r in errs:
            for k, v in r.items():
                if is_err(k):
                    lines.append(f"- `{r['job_id']}` {k}: {v}")
    ro = [r for r in rows if r.get("readout_error")]
    if ro:
        lines += ["", "## Readout error of the used qubits at that calibration", ""]
        for r in ro:
            vals = ", ".join(f"q{q}: {e}" for q, e in r["readout_error"].items())
            lines.append(f"- `{r['job_id']}` ({r.get('backend_reported')}): {vals}")
    return "\n".join(lines) + "\n"


NOTES = {
    False: ("IBM hardware jobs cited in the manuscripts: physical qubits and calibration",
            "Job IDs printed in the manuscripts. They were submitted from an account that no "
            "longer exists (RESULTS_MAP.md, item F2), so any `RuntimeJobNotFound` below is "
            "expected and means the layout is unrecoverable."),
    True: ("Provenance re-campaign (2026-09) IBM jobs: physical qubits and calibration",
           "NEW jobs re-running the same circuits on the live account "
           "(`outputs/provenance_campaign/ledger.md`). They are not the runs behind the "
           "paper's numbers; do not report these layouts as the paper's."),
}


def main() -> None:
    from qiskit_ibm_runtime import QiskitRuntimeService

    use_ledger = "--ledger" in sys.argv
    service = QiskitRuntimeService()
    rows = []
    for record in (ledger_jobs() if use_ledger else expected_jobs()):
        if str(record.get("backend", "")).startswith("ionq"):
            continue
        print(f"[fetch] {record['job_id']} ({record.get('campaign')})", flush=True)
        try:
            rows.append(fetch(service, record))
        except Exception as exc:  # noqa: BLE001
            rows.append({**record, "fetch_error": repr(exc)})

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stem = "job_layouts_ledger" if use_ledger else "job_layouts"
    (OUT_DIR / f"{stem}.json").write_text(json.dumps(rows, indent=2, default=str))
    (OUT_DIR / f"{stem}.md").write_text(to_markdown(rows, *NOTES[use_ledger]))
    print(f"[done] wrote {OUT_DIR / f'{stem}.md'}")


if __name__ == "__main__":
    main()
