"""Regenerate RESULTS_MAP.md's §F4 block from the provenance campaign ledger.

§F2 records why the manuscripts' job identifiers can never be retrieved again. §F4 is
its counterpart: the jobs that *can*. Kept generated rather than hand-written so the
section cannot drift from ledger.jsonl as stages land.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LEDGER = REPO_ROOT / "IBM_Cloud" / "outputs" / "provenance_campaign" / "ledger.jsonl"
MAP = REPO_ROOT / "overleaf_docs" / "RESULTS_MAP.md"
START = "<!-- BEGIN F4 (generated by IBM_Cloud/write_f4_section.py) -->"
END = "<!-- END F4 -->"

EXPECTED = {"ibm": 15, "ionq": 10}


def build() -> str:
    records, seen = [], set()
    for line in LEDGER.read_text().splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        job_id = record.get("job_id")
        if job_id and job_id not in seen:
            seen.add(job_id)
            records.append(record)

    crns = sorted({r["account"].get("instance") for r in records if r.get("account", {}).get("instance")})
    counts = {"ibm": sum(r["provider"] == "ibm" for r in records),
              "ionq": sum(r["provider"] == "ionq" for r in records)}
    complete = all(counts[k] >= EXPECTED[k] for k in EXPECTED)

    out = [START, "", "## F4. Re-execution campaign (2026-09-05)", "",
           "The jobs in §F2 cannot be retrieved. These can. Same circuits, rebuilt from the same",
           "checkpoints, re-executed under a live instance in the student's active account so the",
           "submission has service-side evidence a referee can check.", "",
           "**These numbers do not replace the manuscripts' numbers, and must not be swapped into",
           "their tables.** A job identifier and a PSNR are a matched pair: the values below are what",
           "*these* jobs returned, on hardware calibrated months after the originals. Pairing a new",
           "identifier with an old PSNR would produce a table that contradicts itself the moment",
           "anyone retrieves the job -- which, unlike before, they now can.", ""]

    if not complete:
        out += [f"> **Campaign in progress.** {counts['ibm']}/{EXPECTED['ibm']} IBM and "
                f"{counts['ionq']}/{EXPECTED['ionq']} IonQ jobs recorded so far; the remaining",
                "> sweeps are still training locally. This block regenerates as they land.", ""]

    out += [f"- **Instance / CRN:** `{crns[0] if crns else '(none recorded)'}`",
            "- **Driver:** `python IBM_Cloud/run_provenance_campaign.py --stage all`",
            "- **Artifacts:** `IBM_Cloud/outputs/provenance_campaign/` "
            "(`ledger.json`, `ledger.md`, `ledger.tex`, plus each stage's raw output)", ""]

    recon = [r for r in records if r["stage"] in ("pilot", "anchors")]
    if recon:
        out += ["### Reconstruction pilot and anchors — re-executed", "",
                "| Image | Backend | Shots | New job ID | New PSNR (dB) | Printed PSNR (dB) | Δ |",
                "|---|---|---|---|---|---|---|"]
        for r in recon:
            new, old = r.get("psnr_db"), r.get("paper_psnr_db")
            delta = f"{new - old:+.3f}" if (new is not None and old is not None) else "--"
            out.append(f"| {r['label']} | `{r['backend']}` | {r.get('shots')} | `{r['job_id']}` | "
                       f"{new:.3f} | {old:.3f} | {delta} |")
        out.append("")

    replay = [r for r in records if r["stage"] not in ("pilot", "anchors")]
    if replay:
        out += ["### Replay ledger — re-executed", "",
                "| Campaign | Platform | Backend | Shots | New job ID |", "|---|---|---|---|---|"]
        for r in replay:
            platform = "IonQ ideal sim." if r["provider"] == "ionq" else "IBM hardware"
            out.append(f"| {r['label']} | {platform} | `{r['backend']}` | "
                       f"{r.get('shots') or '--'} | `{r['job_id']}` |")
        out.append("")

    out += ["**What this does and does not establish.** It establishes that these circuits run on",
            "real hardware under an account the student controls, and that the identifiers resolve.",
            "It does not recover the provenance of the printed jobs -- that is gone (§F2) -- and it",
            "is not an independent replication of the printed values, since the hardware itself has",
            "changed. The spread between the two columns is a measurement of device variation",
            "between the campaigns, nothing more.", "", END]
    return "\n".join(out)


def main() -> None:
    block = build()
    text = MAP.read_text(encoding="utf-8")
    if START in text and END in text:
        head, rest = text.split(START, 1)
        text = head + block + rest.split(END, 1)[1]
    else:
        marker = "\n---\n\n## F3."
        assert marker in text, "could not find §F3 to insert before"
        text = text.replace(marker, "\n---\n\n" + block + "\n\n---\n\n## F3.", 1)
    MAP.write_text(text, encoding="utf-8")
    print(f"§F4 written to {MAP}")


if __name__ == "__main__":
    main()
